### ISSUE TITLE
PayNow Integration (Idea)

### ISSUE THREAD

**Issue by Surveyor-Jr** [Loydtafireyi/ZimCart#17]
Any plans to integrate with PayNow anytime soon through plugins? Given the situation in Zimbabwe most users would go the Ecocash, OneMoney and VPayments way.

**Comment by Loydtafireyi** [comment]
@Surveyor-Jr  Yes it will be availae in the coming week however still deciding to include it on the premium package or the open source

**Comment by Loydtafireyi** [comment]
@Surveyor-Jr The Paynow issue has been settled and to be released together with the premium version late this week.

**Comment by Surveyor-Jr** [comment]
Thats great. Looking forward to it 😅. 
Thank you
