### ISSUE TITLE
Base table or view not found: 1146 Table 'database.system_settings'

### ISSUE THREAD

**Issue by MouadBNL** [Loydtafireyi/ZimCart#19]
Hey, I tried to run a demo of your app in my local machine and ran to this error when composer tried to generate autoload files :

> Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
   Illuminate\Database\QueryException
  SQLSTATE[42S02]: Base table or view not found: 1146 Table \'zimcart.system_settings\' doesn\'t exist (SQL: select * from `system_settings` limit 1)
  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we\'ll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database\'s errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|
  • A table was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`.
    https://laravel.com/docs/master/migrations#running-migrations
  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
      +2 vendor frames
  4   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

and even when i try to run my migration a run to the same error, and I have no idea how to fix it. Please help

**Comment by Loydtafireyi** [comment]
@MouadBNL Please follow all the installation instructions

You need to comment some code first then uncomment after installation

[run git clone https://github.com/Loydtafireyi/zimcart.git].
[Then navigate to App\Providers\AppServiceProvder and comment out all the View::share in the boot method].
run composer update .
run npm install.
run npm run dev.
run php artisan key:generate.
set up your database in the .env
run php artisan migrate.
run php artisan db:seed.
run php artisan storage:link.
[Then navigate back App\Providers\AppServiceProvder and uncomment out all the View::share in the boot method].
run php artisan serve

**Comment by MouadBNL** [comment]
Sorry I didn't comment line, Thank you!
