### ISSUE TITLE
Login With google showing 400 Client Id missing

### ISSUE THREAD

**Issue by msamgan** [Loydtafireyi/ZimCart#5]
At the time of checkout if user tries to login with google, its showing **400 Error**

![image](https://user-images.githubusercontent.com/29948727/93797053-c9b4ba00-fc4c-11ea-92bb-840912d6f0e3.png)

**Comment by Loydtafireyi** [comment]
@msamgan you need to provide the client and secret id in your .env you can use the following link to get your credentials https://developers.google.com/identity/sign-in/web/sign-in

**Comment by msamgan** [comment]
Thanks.
Ill check it out but can you plelsae mention this is you documentation as it woluld be of a great help for the new users...

**Comment by Loydtafireyi** [comment]
@msamgan thanks for that I will update the docs

**Comment by Loydtafireyi** [comment]
updated the docs

**Comment by msamgan** [comment]
now its better.
no confusion..

**Comment by Loydtafireyi** [comment]
@msamgan Thanks man. I hope you liked the script....
