### ISSUE TITLE
Database SQL file missing

### ISSUE THREAD

**Issue by mhaeeb** [Loydtafireyi/ZimCart#59]
Hello Sir,

Please provide the .sql file foe the database configuration. No SQL file found in the code directories. 
Thank you

**Comment by Loydtafireyi** [comment]
@mhaeeb this is a laravel app and does not use SQL files it uses laravel migrations https://laravel.com/docs/10.x/migrations

**Comment by Loydtafireyi** [comment]
Just connect your database via the .env file and run `php artisan migrate` fro the project root
